<?xml version="1.0" encoding="utf-8"?><Database Name="ThiB1Online" Class="DBWebTiengAnhDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-ET1GGIC;Initial Catalog=ThiB1Online;Integrated Security=True" SettingsObjectName="TiengAnhDB.Properties.Settings" SettingsPropertyName="ThiB1OnlineConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDe" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DeThi_ChiTietDeThi" Member="ChiTietDeThis" ThisKey="ID" OtherKey="IDDeThi" Type="ChiTietDeThi" />
      <Association Name="ChuDe_DeThi" Member="ChuDe" ThisKey="IDChuDe" OtherKey="ID" Type="ChuDe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DapAnA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DapAnB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DapAnC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DapAnD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DapAn" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDChiTietChuDe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CauHoi_ChiTietDeThi" Member="ChiTietDeThis" ThisKey="ID" OtherKey="IDCauHoi" Type="ChiTietDeThi" />
      <Association Name="ChiTietChuDe_CauHoi" Member="ChiTietChuDe" ThisKey="IDChiTietChuDe" OtherKey="ID" Type="ChiTietChuDe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietChuDe" Member="ChiTietChuDes">
    <Type Name="ChiTietChuDe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IDChuDe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiTietChuDe_CauHoi" Member="CauHois" ThisKey="ID" OtherKey="IDChiTietChuDe" Type="CauHoi" />
      <Association Name="ChuDe_ChiTietChuDe" Member="ChuDe" ThisKey="IDChuDe" OtherKey="ID" Type="ChuDe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDeThi" Member="ChiTietDeThis">
    <Type Name="ChiTietDeThi">
      <Column Name="IDDeThi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCauHoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CauHoi_ChiTietDeThi" Member="CauHoi" ThisKey="IDCauHoi" OtherKey="ID" Type="CauHoi" IsForeignKey="true" />
      <Association Name="DeThi_ChiTietDeThi" Member="DeThi" ThisKey="IDDeThi" OtherKey="ID" Type="DeThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChuDe" Member="ChuDes">
    <Type Name="ChuDe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChuDe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChuDe_DeThi" Member="DeThis" ThisKey="ID" OtherKey="IDChuDe" Type="DeThi" />
      <Association Name="ChuDe_ChiTietChuDe" Member="ChiTietChuDes" ThisKey="ID" OtherKey="IDChuDe" Type="ChiTietChuDe" />
    </Type>
  </Table>
</Database>